#!/usr/bin/env perl

use lib './lib';
use Modern::Perl;
use Cwd qw'cwd abs_path';
use File::Basename;
use File::Spec;
use Data::Dumper;

use Log::UDP::Daemon;

# default config
my $yaml_configfile = $ARGV[1]
						|| $ENV{LOG_UDP_DAEMON_CONF}
						|| abs_path(dirname(__FILE__)).'/conf/default.yaml';

Log::UDP::Daemon->start($yaml_configfile);
