---
daemon:
  name: log_udp_daemon
  pid: /tmp/log_udp_daemon.pid
  foreground: 0
server:
  port: 9011
logging:
  driver: LogFile
MongoDB:
  host: localhost
  port: 9002
  db: log_daemon
  fields:
    - class
    - method
    - hostname
    - timestamp
LogFile:
  prefix: udplog_
  ext: log
  path: /tmp
  fields:
    - timestamp
    - hostname
    - class
    - method
    - level
    - data
MySQL:
  host: localhost
  port: 3306
  db: test
  user: root
  pass: xpto
  fields:
    - timestamp
    - hostname
    - class
    - method
  optional:
    - user_id
